### ISSUE TITLE
c++ missing keyword highlighting

### ISSUE THREAD

**Issue by SreenivasVRao** [ianpan870102/vscode-dark-emacs-theme#1]
Hi, thank you so much for this great theme. Just wondering if this is an issue that has any fix...

![image](https://user-images.githubusercontent.com/18532038/72950774-2750d980-3d41-11ea-8169-d442a1ae4815.png)

**Comment by ianpan870102** [comment]
Well, this theme is meant to be minimal. Have you tried this one: https://github.com/ianpan870102/vscode-dark-plus-emacs-theme?

**Comment by SreenivasVRao** [comment]
https://imgur.com/a/UiVO5v9

I tried both. Maybe it is just personal preference. I like VSCode dark+ quite a lot, but the colour palette seems smaller than spacemacs-dark. Thanks anyhow for such a nice theme!

**Comment by ianpan870102** [comment]
Thanks for the kind words.
I've added a lot more support for https://github.com/ianpan870102/vscode-dark-plus-emacs-theme in the past couple months. Please try it out
Feel free to reopen if you have more concerns
